description: image to tikz code using gemma4:e2b-it-qat


prompts:
  - |
    Convert this image into complete LaTeX/TikZ code.
    Return only the full LaTeX document.
    Do not use markdown fences.
    Do not add explanations.

providers:
  - id: http://127.0.0.1:8004/generate
    label: ollama-fastapi
    config:
      method: POST
      timeout: 900000
      headers:
        Content-Type: application/json
      body:
        prompt: "{{prompt}}"
        image: "{{reference_image}}"
        model: "gemma4:e2b-it-qat"
      responseParser: json.output

defaultTest:
  vars:
    debug: true

    timeout: 60
    crystalbleu_k: 500
    crystalbleu_n: 4
    lpips_net_type: alex
    crystalbleu_use_cache: true

  assert:
    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/image_structural_similarity.py
      metric: image_ssim
      config:
        threshold: 0.75

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/tikz_is_renderable.py
      metric: renderable

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/tikz_crystalbleu.py
      metric: crystalbleu
      config:
        threshold: 0.1
        crystalbleu_corpus: /usr/prakt/s0030/projects/data/benchmark_data/references

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/tikz_ted.py
      metric: ted_similarity
      config:
        threshold: 0.5

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/image_clip_similarity.py
      metric: clip_similarity
      config:
        threshold: 0.6

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/image_siglip_similarity.py
      metric: siglip_similarity
      config:
        threshold: 0.6

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/image_siglip_cc.py
      metric: siglip_cc
      config:
        threshold: 0.7

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/image_lpips.py
      metric: lpips_similarity
      config:
        threshold: 0.8

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/image_dreamsim.py
      metric: dreamsim_similarity
      config:
        threshold: 0.75

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/image_dists.py
      metric: dists_distance
      config:
        threshold: 0.8

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/tikz_relative_length_output_reference.py
      metric: relative_length_error
      config:
        threshold: 0.8

    - type: python
      value: file:///usr/prakt/s0030/projects/tikzcodegenerator/evaluation/promptfoo/assertions/image_ms_structual_similarity.py
      metric: ms-ssim
      config:
        threshold: 0.75

tests: file:///usr/prakt/s0030/projects/data/benchmark_data/image_manifest.csv