description: Image-to-TikZ benchmark

prompts:
  - image-to-tikz

providers:
  - id: http
    label: geotikzbridge-8b
    config:
      url: "http://127.0.0.1:8007/geotikzbridge"
      method: POST
      timeout: 900000
      validateStatus: "status >= 200 && status < 300"
      multipart:
        parts:
          - kind: file
            name: image
            filename: input.png
            contentType: image/png
            source:
              type: path
              path: "file://{{reference_image}}"

          - kind: file
            name: llm_description
            filename: description.txt
            contentType: text/plain
            source:
              type: path
              path: "file://{{llm_description}}"

          - kind: field
            name: prompt
            value: "{{prompt}}"

          - kind: field
            name: use_llm_description
            value: "true"

          - kind: field
            name: debug
            value: "true"

      transformResponse: json.tikz

defaultTest:
  assert:
    - type: python
      value: file://../assertions/tikz_is_renderable.py
      metric: renderable
    - type: python
      value: file://../assertions/image_structural_similarity.py
      metric: image_ssim
    - type: python
      value: file://../assertions/image_ms_structural_similarity.py
      metric: image_ms_ssim
    - type: python
      value: file://../assertions/image_clip_similarity.py
      metric: clip_similarity
    - type: python
      value: file://../assertions/image_siglip_similarity.py
      metric: siglip_similarity
    - type: python
      value: file://../assertions/image_lpips.py
      metric: lpips_similarity
    - type: python
      value: file://../assertions/image_dreamsim.py
      metric: dreamsim_similarity
    - type: python
      value: file://../assertions/image_dists.py
      metric: dists_similarity
    - type: python
      value: file://../assertions/tikz_crystalbleu.py
      metric: crystalbleu
    - type: python
      value: file://../assertions/tikz_ted.py
      metric: ted_similarity
    - type: python
      value: file://../assertions/tikz_relative_length_output_reference.py
      metric: relative_length_similarity

tests: file://../tests.py:generate_tests
