description: vlm description to tikz code using tikzilla-8b-sft

prompts:
  - "{{caption}}"

providers:
  - id: http
    label: tikzilla-8b-sft
    config:
      url: http://host.docker.internal:8005/tikzilla_sft
      method: POST
      headers:
        Content-Type: application/json
      body:
        text: "{{caption}}"
      transformResponse: json.tikz

  
defaultTest:
  vars:
    debug: true

    timeout: 6
    crystalbleu_k: 500
    crystalbleu_n: 1
    lpips_net_type: alex
    crystalbleu_use_cache: true

  assert:
    - type: python
      value: file:///app/assertions/image_structural_similarity.py
      metric: image_ssim
      config:
        threshold: 0.75

    - type: python
      value: file:///app/assertions/tikz_is_renderable.py
      metric: renderable

    - type: python
      value: file:///app/assertions/tikz_crystalbleu.py
      metric: crystalbleu
      config:
        threshold: 0.1

    - type: python
      value: file:///app/assertions/tikz_crystalbleu_from_scitikzer.py
      metric: crystalbleu_scitikzer
      config:
        threshold: 0.1

    - type: python
      value: file:///app/assertions/tikz_ted.py
      metric: ted_similarity
      config:
        threshold: 0.5

    - type: python
      value: file:///app/assertions/tikz_ted_from_scitikzer.py
      metric: ted_similarity_scitikzer
      config:
        threshold: 0.5

    - type: python
      value: file:///app/assertions/image_clip_similarity.py
      metric: clip_similarity
      config:
        threshold: 0.6

    - type: python
      value: file:///app/assertions/image_siglip_similarity.py
      metric: siglip_similarity
      config:
        threshold: 0.6

    - type: python
      value: file:///app/assertions/image_siglip_cc.py
      metric: siglip_cc
      config:
        threshold: 0.7

    - type: python
      value: file:///app/assertions/image_lpips.py
      metric: lpips_similarity
      config:
        threshold: 0.8

    - type: python
      value: file:///app/assertions/image_dreamsim.py
      metric: dreamsim_similarity
      config:
        threshold: 0.75

    - type: python
      value: file:///app/assertions/image_dists.py
      metric: dists_distance
      config:
        threshold: 0.8

    - type: python
      value: file:///app/assertions/tikz_relative_length_output_reference.py
      metric: relative_length_error
      config:
        threshold: 0.8

    - type: python
      value: file:///app/assertions/image_ms_structual_similarity.py
      metric: ms-ssim
      config:
        threshold: 0.75

tests: file:///image_manifest.csv